Encodings generated by migrations should not be treated as regular nodes in a few
specific places.

Let's consider the following bit of code:

  $ cat > test.ml << EOF
  > let x = (~a:1, ~b:2)
  > let y = [%some_ext 4]
  > EOF

Once migrated to our AST, this will contain two extension points, the
`[%some_ext 4]` from the source code, and the encoded labeled tuple.

The former should trigger the extension check while the latter should not:

  $ ./id_driver.exe -check -check-on-extensions test.ml
  [%%ocaml.error "Extension `some_ext' was not translated"]
  let x =
    [%ppxlib.migration.pexp_labeled_tuple_5_4
      (((`Some `a), 1), ((`Some `b), 2))]
  let y = [%some_ext 4]


The following driver has a global transformation registered that turns all
integer litterals `i` into the litteral `i+1`.
By default traversal classes should not recurse into encodings' payload:

  $ ./traversal_driver.exe test.ml
  let x =
    [%ppxlib.migration.pexp_labeled_tuple_5_4
      (((`Some `a), 2), ((`Some `b), 3))]
  let y = [%some_ext 5]

